### ISSUE TITLE
How to hide the skip button on last target?

### ISSUE THREAD

**Issue by Wesleychung93** [RafaelBarbosatec/tutorial_coach_mark#103]
I understood there is a `hideSkip` property when initializing the `TutorialCoachMark`, Appreciate could you guide how to hide skip button on last/final target ?

**Comment by Wesleychung93** [comment]
@chenrilima What's the point adding skip button on last step/target from tutorial ? IMO, the skip button should be hide automatically when reach to last step from tutorial

**Comment by dragongesa** [comment]
absolutely agreed

**Comment by pratik97179** [comment]
@Wesleychung93 There is no way to conditionally show or hide the built-in skip button but there is a workaround for this. You will have to add the skip button as a `TargetContent` for each `target` and in the `onTap` property, you can call the `skip()` method on your `TutorialCoachMark` variable. Don't add the skip button on the last screen. It's can cause code redundancy, but this is the only way by which we can have the skip button removed from the last screen

**Comment by atrope** [comment]
IMHO this should be a breaking change and we should have the option to show "Skip" or Any other text/widget we want in the last (or only) target.

In our app it changed the behaviour of our 1-step tutorial and user now need to click the target only instead of the "ok" to skip.

I urge you to reconsider @RafaelBarbosatec or at least make it optional.

**Comment by RafaelBarbosatec** [comment]
Good point @atrope ! I will make it optional!

**Comment by atrope** [comment]
@RafaelBarbosatec 1.2.7 is ok the only thing i would argue is that for this is  to be a non-breaking change `showSkipInLastTarget` should be true by default.
