### ISSUE TITLE
The getter 'offset' was called on null.

### ISSUE THREAD

**Issue by yanisG** [RafaelBarbosatec/tutorial_coach_mark#49]
I/flutter (11367): ERROR: Não foi possivem oter informações da KEY

======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building TutorialCoachMarkWidget-[LabeledGlobalKey<TutorialCoachMarkWidgetState>#24a8a](dirty, dependencies: [MediaQuery], state: TutorialCoachMarkWidgetState#35e8e):
The getter 'offset' was called on null.
Receiver: null
Tried calling: offset

when i use bottomntaped to move to another tab this shows up

**Comment by RafaelBarbosatec** [comment]
Whenever you are going to have the tutorial displayed, give it a little delay so that you have time to build and render the widget tree.

**Comment by yanisG** [comment]
@RafaelBarbosatec  how you can achieve that  ? how you can give a delay to the next targetfocus ..

**Comment by yanisG** [comment]
when an user click the first target he will change the tab : 
onClickTarget: (target) {
// here code to change tab "bottomtaped(3)" to change 
}
after the first target how to delay the next target to show

**Comment by RafaelBarbosatec** [comment]
Hmm, now I understand what you're trying to do. You cannot create a single tutorial with the content of all tabs. Because not all widgets have been rendered, so I can't get their option.
In this case, create a tutorial for each tab separately. Then when you click on the second Tab you start the tutorial regarding the widgets of that tab
